### ISSUE TITLE
"Missingrequired request header. Must specify one of: origin,x-requested-with" - Error loading XML

### ISSUE THREAD

**Issue by weirdyang** [OKCody/News#39]
Hi, I'm trying to load the weather forecast from this RSS feed, but I am getting this error in the console.  
  `HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(Fetch)GET -"https://cody-cors.herokuapp.com/https://www.weather.gov.sg/files/rss/rss24HrForecast.xml"`

When I navigate to the link provided, I get this message:

"Missingrequired request header. Must specify one of: origin,x-requested-with" - Error loading XML

**Comment by OKCody** [comment]
Hi there! 

I tried removing `requireHeader: ['origin', 'x-requested-with']` from my cors-anywhere instance and found that https://www.weather.gov.sg . . . still does not work, but http://www.weather.gov.sg . . . does work. 

Ultimately, using HTTP works but HTTPS not. I'm not exactly sure why, but there appears to be a difference in the way that the server responds to each of these. `¯\_(ツ)_/¯ `

**Comment by weirdyang** [comment]
Ahh cool: thanks!
